import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const viewport=document.querySelector('#viewport'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=2;controls.maxDistance=40;controls.target.set(0,0,0);
scene.add(new THREE.HemisphereLight(0xbfdcff,0x172331,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(5,8,6);scene.add(key);const fill=new THREE.DirectionalLight(0x6eb8ff,1.8);fill.position.set(-6,4,-4);scene.add(fill);const grid=new THREE.GridHelper(20,20,0x24445c,0x132a3c);grid.position.y=-1.1;scene.add(grid);
let model,auto=false;const markers=[];const risks=[{title:'屋面临边防护不足',text:'AI识别：屋面与二层临边区域存在防护连续性不足的潜在高处坠落风险。',recommend:'建议：设置连续临边防护栏杆，并复核安全警示与作业边界。',confidence:'AI 94.7%'},{title:'高处作业人员防护',text:'AI识别：东侧立面高处作业区域存在个人防护用品佩戴与使用状态需复核的问题。',recommend:'建议：复核安全带、安全帽等PPE，并进行作业前安全确认。',confidence:'AI 91.2%'},{title:'施工通道占用',text:'AI识别：入口区域可能存在材料临时堆放导致通行空间受限的风险。',recommend:'建议：清理通道、划定材料堆放区并设置醒目标识。',confidence:'AI 88.5%'}];
function fit(){const r=viewport.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}window.addEventListener('resize',fit);fit();
new GLTFLoader().load('assets/building.glb',g=>{model=g.scene;scene.add(model);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.scale.setScalar(5/Math.max(size.x,size.y,size.z));model.position.y=-1;camera.position.set(7,4.5,7);controls.update();document.querySelector('#loading').style.display='none';addMarkers()},undefined,()=>{document.querySelector('#loading').innerHTML='<b>模型加载失败</b><span>请确认 assets/building.glb 已上传</span>'});
function addMarkers(){[[.55,.95,.25],[-.65,.35,.28],[.02,-.35,.65]].forEach((p,i)=>{const el=document.createElement('button');el.className='risk-marker';el.textContent='!';el.style.cssText=`position:absolute;width:25px;height:25px;border-radius:50%;border:2px solid #fff;background:${i?'#b97925':'#dc4655'};color:#fff;font-weight:900;box-shadow:0 0 20px ${i?'#ffb34d88':'#ff5d6888'};display:none;z-index:4;cursor:pointer`;viewport.appendChild(el);markers.push({el,pos:new THREE.Vector3(...p)});el.onclick=()=>pick(i)})}function updateMarkers(){if(!model)return;const r=viewport.getBoundingClientRect();markers.forEach(m=>{const v=m.pos.clone();model.localToWorld(v);v.project(camera);m.el.style.display=v.z<1?'grid':'none';m.el.style.left=((v.x*.5+.5)*r.width-12)+'px';m.el.style.top=((-v.y*.5+.5)*r.height-12)+'px'})}function pick(i){const x=risks[i];document.querySelector('#detailTitle').textContent=x.title;document.querySelector('#confidence').textContent=x.confidence;document.querySelector('#detailText').textContent=x.text;document.querySelector('#recommend').textContent=x.recommend;document.querySelectorAll('.risk-card').forEach((e,n)=>e.classList.toggle('selected',n===i))}
document.querySelectorAll('.risk-card').forEach((e,i)=>e.onclick=()=>pick(i));const views={iso:[7,4.5,7],front:[0,2.3,9],side:[9,2.3,0],rear:[0,2.3,-9]};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');camera.position.set(...views[b.dataset.view]);controls.target.set(0,0,0);controls.update()});document.querySelector('#auto').onclick=()=>{auto=!auto;document.querySelector('#auto').classList.toggle('active',auto)};document.querySelector('#scan').onclick=()=>{const s=document.querySelector('#scanStatus'),score=document.querySelector('#score');s.textContent='SCANNING';let n=0;const t=setInterval(()=>{n++;score.textContent=String(72+Math.floor(Math.random()*5));if(n>12){clearInterval(t);score.textContent='72';s.textContent='LIVE'}},80)};document.querySelector('#report').onclick=()=>document.querySelector('#modal').classList.add('show');document.querySelector('#close').onclick=()=>document.querySelector('#modal').classList.remove('show');document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')};function animate(){requestAnimationFrame(animate);if(auto&&model)model.rotation.y+=.0025;controls.update();renderer.render(scene,camera);updateMarkers()}animate();